### ISSUE TITLE
Implement PRG packages

### ISSUE THREAD

**Issue by BrokenR3C0RD** [Minxrod/PTC-Interpreter#4]
https://petitcomputer.fandom.com/wiki/PTC_File_Formats#PRG_File
Might want to take a look at this. Basically, there was an option to save programs as packages, which outputted one .PTC file and a lot of QR codes. The other files were just chucked into the end of the file. Stuff like Village and MM2PTC use this.

I would help with this but I don't know Java and I don't want to learn it. I'm starting something similar in JavaScript if you're interested. If so, message me on Discord: @MasterR3C0RD#7695

**Comment by Minxrod** [comment]
Interesting, this saves a lot of time trying to research for packages and I need to redesign the file loading anyways. Thanks.

**Comment by BrokenR3C0RD** [comment]
Also, I ask that if you figure out how SCR files are stored, that you add it to the wiki page linked in the fist post. That one's still a bit tricky.

**Comment by Versalys** [comment]
Hey MinxRod, in the interest of keeping privacy I will just say I am the guy sitting on your left doing the c++ stuff in APCSA with RonCon. Is there anyway I could reach out to you for questions minx? Stackoverflow is alright but you have been good at helping me out in the past.

Thanks
-Versalys

**Comment by Minxrod** [comment]
This will not be implemented in this version. Eventually this will be implemented into the new  version.
