### ISSUE TITLE
NullPointerException on Ubuntu

### ISSUE THREAD

**Issue by LegionMammal978** [Minxrod/PTC-Interpreter#6]
In Ubuntu, attempting to load a file yields only a black screen and a series of `NullPointerException`s in the console. The issue lies in the `PetitComGUI` constructor. Lines 99–104 of `PetitComGUI.java` add the `total` panel to the frame, and line 107 initializes `processor`. However, the former set of lines indirectly ends up calling `PetitComGUI.NPanel.paintComponent` multiple times. This method references `processor.getImage`, which raises the exceptions, since `processor` has not yet been initialized. Exchanging lines 99–104 with line 107 appears to fix this bug.

**Comment by Minxrod** [comment]
Well, I missed this issue by a couple years.
The solution now is to switch to the newer version, located at https://github.com/Minxrod/PTC-EmkII. 
If you still want to, feel free to make the change and create a pull request, but I'm not supporting this version anymore.

**Comment by LegionMammal978** [comment]
Thank you; I was mainly using this program since I couldn't find anything else that worked. The new version should work for my purposes.
